library(Deriv)
print("input your function")
func <- as.character(readline())
variablee <- as.character(readline(prompt = "enter your variable"))
pratical_derivative <- Deriv(func,"x")
print(pratical_derivative)
print("输入x")
x0 <- as.numeric(readline())
print("输入y")
y0 <- as.numeric(readline())
expr <- sub("x",x0,pratical_derivative)
expr <- sub("y",y0,expr)
result <- eval(parse(text = expr))
print(result)

